"""Add updated_at and updated_by to sales_rates

Revision ID: 9b2f041ecf3d
Revises: ab22f705ed6d
Create Date: 2026-01-21 10:07:59.679752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2f041ecf3d'
down_revision: Union[str, Sequence[str], None] = 'ab22f705ed6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_rates', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sales_rates', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales_rates', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_rates', type_='foreignkey')
    op.drop_column('sales_rates', 'updated_by')
    op.drop_column('sales_rates', 'updated_at')
    # ### end Alembic commands ###
